import { useEffect, useRef, useState, type ReactNode } from "react";
import { SearchIcon } from "../icon/icon";
import "./command-menu.css";

export interface CommandMenuItem { key: string; label: ReactNode; textValue: string; icon?: ReactNode; meta?: ReactNode; group?: string; disabled?: boolean }
export interface CommandMenuProps { open: boolean; onClose?: () => void; items: readonly CommandMenuItem[]; onSelect?: (item: CommandMenuItem) => void; query?: string; onQueryChange?: (query: string) => void; placeholder?: string; emptyText?: ReactNode; escapeLabel?: string; groupLabels?: Readonly<Record<string, ReactNode>>; filter?: (item: CommandMenuItem, query: string) => boolean; label?: string }
export function CommandMenu({ open, onClose, items, onSelect, query, onQueryChange, placeholder = "Search or enter a command…", emptyText = "No matching commands", escapeLabel = "ESC", groupLabels, filter = (item, text) => item.textValue.toLowerCase().includes(text.toLowerCase()), label = "Command menu" }: CommandMenuProps) {
  const [internalQuery, setInternalQuery] = useState(""); const [selected, setSelected] = useState(0); const inputRef = useRef<HTMLInputElement>(null); const value = query ?? internalQuery; const visible = value.trim() ? items.filter((item) => filter(item, value.trim())) : [...items];
  useEffect(() => { if (!open) return; setSelected(0); if (query == null) setInternalQuery(""); const frame = requestAnimationFrame(() => inputRef.current?.focus()); return () => cancelAnimationFrame(frame); }, [open, query]);
  useEffect(() => { if (selected >= visible.length) setSelected(Math.max(0, visible.length - 1)); }, [selected, visible.length]);
  if (!open) return null;
  const choose = (item: CommandMenuItem | undefined) => { if (!item || item.disabled) return; onSelect?.(item); };
  const groups = visible.reduce<Array<[string, CommandMenuItem[]]>>((result, item) => { const key = item.group ?? ""; const existing = result.find(([group]) => group === key); if (existing) existing[1].push(item); else result.push([key, [item]]); return result; }, []);
  let flatIndex = 0;
  return <div className="gd-command-scrim" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose?.(); }}><div className="gd-command" role="dialog" aria-modal="true" aria-label={label}><div className="gd-command-search"><SearchIcon size={16} /><input ref={inputRef} value={value} onChange={(event) => { const next = event.target.value; if (query == null) setInternalQuery(next); onQueryChange?.(next); setSelected(0); }} onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); setSelected((index) => Math.min(index + 1, visible.length - 1)); } else if (event.key === "ArrowUp") { event.preventDefault(); setSelected((index) => Math.max(index - 1, 0)); } else if (event.key === "Enter") { event.preventDefault(); choose(visible[selected]); } else if (event.key === "Escape") { event.preventDefault(); onClose?.(); } }} placeholder={placeholder} aria-controls="gd-command-results" aria-activedescendant={visible[selected] ? `gd-command-${visible[selected].key}` : undefined} /><kbd>{escapeLabel}</kbd></div><div className="gd-command-results" id="gd-command-results" role="listbox">{visible.length === 0 ? <div className="gd-command-empty">{emptyText}</div> : null}{groups.map(([group, groupItems]) => <div key={group || "default"} className="gd-command-group">{group ? <div className="gd-command-group-label">{groupLabels?.[group] ?? group}</div> : null}{groupItems.map((item) => { const index = flatIndex; flatIndex += 1; return <button type="button" id={`gd-command-${item.key}`} key={item.key} role="option" aria-selected={index === selected} disabled={item.disabled} className={`gd-command-row${index === selected ? " gd-command-row--selected" : ""}`} onMouseMove={() => setSelected(index)} onClick={() => choose(item)}>{item.icon ? <span className="gd-command-icon">{item.icon}</span> : null}<span className="gd-command-label">{item.label}</span>{item.meta ? <span className="gd-command-meta">{item.meta}</span> : null}{index === selected ? <kbd>↵</kbd> : null}</button>; })}</div>)}</div></div></div>;
}
