[package]
name = "gooddealer-desktop-tauri"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dependencies]
gooddealer-local-storage = { path = "../../../crates/local-storage" }
gooddealer-secure-host-core = { path = "../../../crates/secure-host-core" }
serde.workspace = true
serde_json.workspace = true
tauri.workspace = true

[dev-dependencies]
tempfile = "=3.27.0"

[lints]
workspace = true
