import { useEffect, useRef, useState, type CSSProperties, type Key, type ReactNode } from "react";
import { Checkbox } from "../checkbox/checkbox";
import "./table.css";

export type TableColumnPriority = "essential" | "secondary" | "supplementary";
export interface TableColumn<Row = Record<string, unknown>> { key: string; label?: ReactNode; numeric?: boolean; align?: "left" | "right" | "center"; width?: number | string; muted?: boolean; sortable?: boolean; priority?: TableColumnPriority; render?: (row: Row, index: number) => ReactNode }
export interface TableVirtualWindow { startIndex: number; endIndex: number; beforeHeight?: number; afterHeight?: number }
export interface TableProps<Row = Record<string, unknown>> { columns: readonly TableColumn<Row>[]; rows: readonly Row[]; rowKey?: keyof Row | ((row: Row, index: number) => Key); density?: "compact" | "regular" | "spacious"; selectable?: boolean; selected?: readonly Key[]; onSelectionChange?: (keys: Key[]) => void; sortKey?: string; sortDir?: "asc" | "desc"; onSort?: (key: string, dir: "asc" | "desc") => void; onRowClick?: (row: Row) => void; hover?: boolean; maxHeight?: number | string; footer?: ReactNode; emptyText?: ReactNode; responsive?: boolean; forceWidth?: number | null; bpSecondary?: number; bpSupplementary?: number; virtualWindow?: TableVirtualWindow; style?: CSSProperties; hiddenColumnsLabel?: (count: number) => ReactNode; label?: string }

export function getVisibleColumns<Row>(columns: readonly TableColumn<Row>[], width: number | null, bpSecondary = 640, bpSupplementary = 900) { if (width == null) return columns; return columns.filter((column) => column.priority !== "secondary" ? column.priority !== "supplementary" || width >= bpSupplementary : width >= bpSecondary); }
function SortGlyph({ dir }: { dir: "asc" | "desc" }) { return <svg aria-hidden="true" width="8" height="10" viewBox="0 0 8 10" fill="none"><path d={dir === "desc" ? "M1 4L4 8L7 4" : "M1 6L4 2L7 6"} stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" /></svg>; }

export function Table<Row>({ columns, rows, rowKey = "id" as keyof Row, density = "regular", selectable = false, selected = [], onSelectionChange, sortKey, sortDir = "asc", onSort, onRowClick, hover = true, maxHeight, footer, emptyText = "No matching items", responsive = true, forceWidth = null, bpSecondary = 640, bpSupplementary = 900, virtualWindow, style, hiddenColumnsLabel = (count) => `${count} columns hidden`, label }: TableProps<Row>) {
  const shellRef = useRef<HTMLDivElement>(null); const [measuredWidth, setMeasuredWidth] = useState<number | null>(null);
  useEffect(() => { if (!responsive || forceWidth != null || typeof ResizeObserver === "undefined") return; const element = shellRef.current; if (!element) return; const observer = new ResizeObserver((entries) => { const width = entries[0]?.contentRect.width; if (width != null) setMeasuredWidth(width); }); observer.observe(element); return () => observer.disconnect(); }, [forceWidth, responsive]);
  const effectiveWidth = responsive ? forceWidth ?? measuredWidth : null; const shownColumns = getVisibleColumns(columns, effectiveWidth, bpSecondary, bpSupplementary); const hiddenCount = columns.length - shownColumns.length; const selection = new Set(selected);
  const keyOf = (row: Row, index: number): Key => typeof rowKey === "function" ? rowKey(row, index) : ((row[rowKey] as Key | undefined) ?? index); const allKeys = rows.map(keyOf); const allSelected = rows.length > 0 && allKeys.every((key) => selection.has(key)); const someSelected = allKeys.some((key) => selection.has(key));
  const displayedRows = virtualWindow ? rows.slice(Math.max(0, virtualWindow.startIndex), Math.min(rows.length, virtualWindow.endIndex)) : rows; const sourceIndex = (index: number) => virtualWindow ? virtualWindow.startIndex + index : index; const cellClass = (column: TableColumn<Row>) => `${column.numeric || column.align === "right" ? " gd-cell--num" : ""}${column.align === "center" ? " gd-cell--center" : ""}${column.muted ? " gd-cell--muted" : ""}`;
  const toggleAll = () => onSelectionChange?.(allSelected ? [] : allKeys); const toggleOne = (key: Key) => { const next = new Set(selection); if (next.has(key)) next.delete(key); else next.add(key); onSelectionChange?.([...next]); };
  const columnSpan = shownColumns.length + (selectable ? 1 : 0);
  return <div className="gd-table-shell" ref={shellRef} style={style}><div className="gd-table-scroll" style={maxHeight != null ? { maxHeight } : undefined}><table className={`gd-table gd-table--${density}${hover ? " gd-table--hover" : ""}`} aria-label={label}><thead><tr>{selectable ? <th className="gd-cell--check"><Checkbox ariaLabel="Select all rows" checked={allSelected} indeterminate={someSelected && !allSelected} onChange={toggleAll} /></th> : null}{shownColumns.map((column) => <th key={column.key} className={cellClass(column)} style={column.width != null ? { width: column.width } : undefined} aria-sort={sortKey === column.key ? (sortDir === "asc" ? "ascending" : "descending") : undefined}>{column.sortable ? <button type="button" className={`gd-th-sort${sortKey === column.key ? " gd-th-sort--active" : ""}`} onClick={() => onSort?.(column.key, sortKey === column.key && sortDir === "asc" ? "desc" : "asc")}>{column.label}<SortGlyph dir={sortKey === column.key ? sortDir : "asc"} /></button> : column.label}</th>)}</tr></thead><tbody>{virtualWindow?.beforeHeight ? <tr aria-hidden="true"><td colSpan={columnSpan} style={{ height: virtualWindow.beforeHeight, padding: 0, border: 0 }} /></tr> : null}{displayedRows.map((row, visibleIndex) => { const index = sourceIndex(visibleIndex); const key = keyOf(row, index); const isSelected = selection.has(key); return <tr key={key} className={`${isSelected ? "gd-row--selected" : ""}${onRowClick ? " gd-row--clickable" : ""}`} onClick={onRowClick ? () => onRowClick(row) : undefined}>{selectable ? <td className="gd-cell--check"><Checkbox ariaLabel="Select row" stop checked={isSelected} onChange={() => toggleOne(key)} /></td> : null}{shownColumns.map((column) => <td key={column.key} className={cellClass(column)} style={column.width != null ? { width: column.width } : undefined}>{column.render ? column.render(row, index) : (row as Record<string, ReactNode>)[column.key]}</td>)}</tr>; })}{virtualWindow?.afterHeight ? <tr aria-hidden="true"><td colSpan={columnSpan} style={{ height: virtualWindow.afterHeight, padding: 0, border: 0 }} /></tr> : null}</tbody></table>{rows.length === 0 ? <div className="gd-table-empty">{emptyText}</div> : null}</div>{footer || hiddenCount > 0 ? <div className="gd-table-foot">{footer}{hiddenCount > 0 ? <span className="gd-table-hidden">{hiddenColumnsLabel(hiddenCount)}</span> : null}</div> : null}</div>;
}
