import type { CSSProperties, ReactNode } from "react";
import { IconButton } from "../icon-button/icon-button";
import { Select } from "../select/select";
import { ChevronLeftIcon, ChevronRightIcon } from "../icon/icon";
import "./pagination.css";

export interface PaginationProps { page?: number; pageSize?: number; total?: number; onPageChange?: (page: number) => void; onPageSizeChange?: (size: number) => void; pageSizes?: readonly number[]; note?: ReactNode; style?: CSSProperties; labels?: { previous?: string; next?: string; perPage?: string } }
export type PageWindowItem = number | "gap";
export function getPageWindow(current: number, total: number): PageWindowItem[] { if (total <= 7) return Array.from({ length: total }, (_, index) => index + 1); const numbers = [...new Set([1, 2, total - 1, total, current - 1, current, current + 1])].filter((number) => number >= 1 && number <= total).sort((a, b) => a - b); const result: PageWindowItem[] = []; let previous = 0; for (const number of numbers) { if (number - previous > 1) result.push("gap"); result.push(number); previous = number; } return result; }
export function Pagination({ page = 1, pageSize = 25, total = 0, onPageChange, onPageSizeChange, pageSizes = [10, 25, 50, 100], note, style, labels }: PaginationProps) { const size = pageSize > 0 ? pageSize : 25; const pages = Math.max(1, Math.ceil(Math.max(0, total) / size)); const current = Math.min(Math.max(1, page), pages); const from = total === 0 ? 0 : (current - 1) * size + 1; const to = Math.min(total, current * size); return <div className="gd-pager" style={style}><span className="gd-pager-range"><b>{from.toLocaleString()}–{to.toLocaleString()}</b> <span>/ {total.toLocaleString()}</span></span><span className="gd-pager-size">{labels?.perPage ?? "Per page"}<Select size="sm" aria-label={labels?.perPage ?? "Per page"} options={pageSizes.map(String)} value={String(size)} onChange={(event) => onPageSizeChange?.(Number(event.target.value))} /></span>{note ? <span className="gd-pager-note">{note}</span> : null}<span className="gd-pager-nav"><IconButton size="sm" label={labels?.previous ?? "Previous page"} disabled={current <= 1} onClick={() => onPageChange?.(current - 1)}><ChevronLeftIcon size={14} /></IconButton>{getPageWindow(current, pages).map((item, index) => item === "gap" ? <span key={`gap-${index}`} className="gd-pager-gap">…</span> : <button type="button" key={item} className={`gd-pager-num${item === current ? " gd-pager-num--active" : ""}`} aria-current={item === current ? "page" : undefined} onClick={() => onPageChange?.(item)}>{item}</button>)}<IconButton size="sm" label={labels?.next ?? "Next page"} disabled={current >= pages} onClick={() => onPageChange?.(current + 1)}><ChevronRightIcon size={14} /></IconButton></span></div>; }
