// admin-web mock data — GoodDealer operator console (internal). Cross-customer fleet, revenue, infra, support.
window.GD_ADMIN={
  operator:{name:"王运维",email:"ops@gooddealer.com",role:"运营管理员"},
  kpis:{customers:2847,activeCustomers:2413,trials:186,mrr:48210,arr:578520,devicesOnline:1842,devicesBound:4106,syncHealth:99.2,openTickets:23,alerts:3,churnRate:1.8},
  revenueSeries:[38.1,39.4,40.2,41.8,43.0,44.1,45.6,46.2,47.0,47.4,47.9,48.2], // MRR $k by month
  planMix:[{plan:"Professional",count:1806,mrr:36020,color:"var(--gd-gold)"},{plan:"Portfolio",count:214,mrr:9610,color:"var(--gd-blue)"},{plan:"Starter",count:393,mrr:2580,color:"var(--gd-viz-drawdown)"}],
  customers:[
    {id:"C-10428",name:"陈立行",email:"li@quanta.trade",plan:"Professional",status:"active",devices:2,domains:1024,mrr:24.9,since:"2024-03-11",lastSeen:"14:02",country:"CN"},
    {id:"C-10091",name:"Meridian Holdings",email:"ops@meridian.co",plan:"Portfolio",status:"active",devices:5,domains:8420,mrr:74.9,since:"2023-11-02",lastSeen:"13:58",country:"US"},
    {id:"C-11733",name:"Sana Qureshi",email:"sana@qrsh.io",plan:"Professional",status:"past_due",devices:2,domains:612,mrr:24.9,since:"2024-08-19",lastSeen:"2 天前",country:"AE"},
    {id:"C-12055",name:"北岛数字",email:"admin@beidao.cn",plan:"Portfolio",status:"active",devices:4,domains:5109,mrr:74.9,since:"2024-01-27",lastSeen:"12:31",country:"CN"},
    {id:"C-12890",name:"Diego Marín",email:"d@marin.dev",plan:"Starter",status:"trial",devices:1,domains:88,mrr:0,since:"2026-08-02",lastSeen:"09:14",country:"MX"},
    {id:"C-11402",name:"Kestrel Capital",email:"it@kestrel.fund",plan:"Portfolio",status:"active",devices:5,domains:12040,mrr:74.9,since:"2023-06-14",lastSeen:"14:01",country:"GB"},
    {id:"C-13001",name:"Yuki Tanaka",email:"yuki@tnk.jp",plan:"Professional",status:"active",devices:2,domains:430,mrr:24.9,since:"2025-02-08",lastSeen:"昨日",country:"JP"},
    {id:"C-09980",name:"Orbit Domains",email:"team@orbit.io",plan:"Professional",status:"churned",devices:0,domains:0,mrr:0,since:"2023-09-30",lastSeen:"06-28",country:"US"},
    {id:"C-12610",name:"Amara Okafor",email:"amara@okf.ng",plan:"Starter",status:"active",devices:1,domains:142,mrr:8.3,since:"2025-11-15",lastSeen:"11:47",country:"NG"},
    {id:"C-13120",name:"Lindqvist AB",email:"drift@lindqvist.se",plan:"Professional",status:"trial",devices:1,domains:203,mrr:0,since:"2026-08-10",lastSeen:"10:22",country:"SE"},
    {id:"C-10777",name:"Zheng Wei",email:"zw@zheng.co",plan:"Professional",status:"active",devices:2,domains:756,mrr:24.9,since:"2024-05-21",lastSeen:"13:40",country:"CN"},
    {id:"C-11988",name:"Halcyon Group",email:"ops@halcyon.gg",plan:"Portfolio",status:"past_due",devices:3,domains:3301,mrr:74.9,since:"2024-04-03",lastSeen:"3 天前",country:"SG"},
  ],
  fleet:[
    {id:"D-8841",customer:"陈立行",name:"MacBook Pro",os:"macOS 15.2",state:"active",epoch:41,lastSeen:"现在",region:"ap-east-1",health:"ok"},
    {id:"D-8842",customer:"陈立行",name:"iPhone 17 Pro",os:"iOS 19.1",state:"standby",epoch:41,lastSeen:"08:30",region:"ap-east-1",health:"ok"},
    {id:"D-6320",customer:"Meridian Holdings",name:"Mac Studio",os:"macOS 15.1",state:"active",epoch:127,lastSeen:"现在",region:"us-east-1",health:"ok"},
    {id:"D-6321",customer:"Meridian Holdings",name:"ThinkPad X1",os:"Windows 11",state:"standby",epoch:127,lastSeen:"1 小时前",region:"us-east-1",health:"ok"},
    {id:"D-7702",customer:"Kestrel Capital",name:"Precision 5680",os:"Windows 11",state:"active",epoch:88,lastSeen:"现在",region:"eu-west-2",health:"ok"},
    {id:"D-9110",customer:"Sana Qureshi",name:"MacBook Air",os:"macOS 14.6",state:"draining",epoch:53,lastSeen:"2 天前",region:"me-south-1",health:"stale"},
    {id:"D-9111",customer:"Sana Qureshi",name:"iPad Pro",os:"iPadOS 19",state:"activating",epoch:54,lastSeen:"2 天前",region:"me-south-1",health:"warn"},
    {id:"D-5540",customer:"北岛数字",name:"iMac",os:"macOS 15.2",state:"active",epoch:64,lastSeen:"12:31",region:"ap-east-1",health:"ok"},
    {id:"D-4102",customer:"Halcyon Group",name:"Legion Tower",os:"Windows 10",state:"sunset",epoch:31,lastSeen:"3 天前",region:"ap-southeast-1",health:"stale"},
    {id:"D-8003",customer:"Yuki Tanaka",name:"MacBook Pro",os:"macOS 15.0",state:"active",epoch:22,lastSeen:"昨日",region:"ap-northeast-1",health:"ok"},
  ],
  transactions:[
    {id:"TX-88214",customer:"Meridian Holdings",amount:74.9,type:"charge",date:"14:02",method:"Amex · 1005",status:"succeeded"},
    {id:"TX-88213",customer:"陈立行",amount:24.9,type:"charge",date:"13:44",method:"Visa · 4242",status:"succeeded"},
    {id:"TX-88212",customer:"Sana Qureshi",amount:24.9,type:"charge",date:"11:20",method:"Mastercard · 8890",status:"failed"},
    {id:"TX-88210",customer:"Orbit Domains",amount:24.9,type:"refund",date:"昨日",method:"Visa · 3321",status:"succeeded"},
    {id:"TX-88208",customer:"Kestrel Capital",amount:74.9,type:"charge",date:"昨日",method:"Amex · 4400",status:"succeeded"},
    {id:"TX-88205",customer:"北岛数字",amount:74.9,type:"charge",date:"08-15",method:"UnionPay · 6210",status:"succeeded"},
  ],
  services:[
    {name:"Sync API",status:"ok",latency:42,uptime:99.98,note:"p95 · 12 region"},
    {name:"Auth / License",status:"ok",latency:28,uptime:99.99,note:"设备门禁签发"},
    {name:"Cloud Store",status:"ok",latency:61,uptime:99.97,note:"Revision 账本"},
    {name:"Webhooks",status:"degraded",latency:340,uptime:99.4,note:"Afternic 回调延迟"},
    {name:"Billing (Stripe)",status:"ok",latency:88,uptime:99.95,note:"第三方"},
    {name:"Connector Health",status:"warn",latency:0,uptime:98.1,note:"3 平台会话过期率偏高"},
  ],
  incidents:[
    {id:"INC-241",title:"Afternic Webhook 回调延迟升高",sev:"minor",status:"监控中",started:"13:10",svc:"Webhooks"},
    {id:"INC-240",title:"me-south-1 同步队列积压",sev:"minor",status:"已缓解",started:"11:02",svc:"Sync API"},
    {id:"INC-238",title:"Stripe 计划性维护窗口",sev:"info",status:"已完成",started:"08-14",svc:"Billing"},
  ],
  tickets:[
    {id:"T-4821",subject:"设备门禁：移交后无法激活 Standby",customer:"Sana Qureshi",priority:"high",status:"open",assignee:"—",updated:"12 分钟前",channel:"email"},
    {id:"T-4818",subject:"批量改价对 Afternic 未生效",customer:"Meridian Holdings",priority:"high",status:"pending",assignee:"李工",updated:"1 小时前",channel:"in-app"},
    {id:"T-4815",subject:"发票抬头修改申请",customer:"北岛数字",priority:"low",status:"open",assignee:"—",updated:"2 小时前",channel:"email"},
    {id:"T-4809",subject:"Portfolio 多 Workspace 隔离咨询",customer:"Kestrel Capital",priority:"normal",status:"pending",assignee:"王运维",updated:"昨日",channel:"in-app"},
    {id:"T-4802",subject:"过期信用卡扣款失败",customer:"Sana Qureshi",priority:"normal",status:"open",assignee:"—",updated:"昨日",channel:"billing"},
    {id:"T-4790",subject:"导出账户数据请求 (GDPR)",customer:"Yuki Tanaka",priority:"normal",status:"resolved",assignee:"李工",updated:"08-15",channel:"email"},
  ],
  audit:[
    {id:1,actor:"王运维",action:"强制解绑设备",target:"D-4102 · Halcyon Group",time:"13:55",ip:"10.0.4.21"},
    {id:2,actor:"系统",action:"扣款失败 · 自动重试",target:"C-11733 · Sana Qureshi",time:"11:21",ip:"—"},
    {id:3,actor:"李工",action:"手动退款 $24.90",target:"C-09980 · Orbit Domains",time:"昨日 17:40",ip:"10.0.4.9"},
    {id:4,actor:"王运维",action:"切换功能开关 batch_v2",target:"全局 · 12% rollout",time:"昨日 15:02",ip:"10.0.4.21"},
    {id:5,actor:"王运维",action:"发布公告",target:"ANN-0042 · 全部客户",time:"昨日 10:30",ip:"10.0.4.21"},
    {id:6,actor:"系统",action:"签发 ActiveDeviceLease",target:"D-8003 · Yuki Tanaka · Epoch 22",time:"08-15 09:12",ip:"—"},
    {id:7,actor:"李工",action:"重置客户 2FA",target:"C-12055 · 北岛数字",time:"08-15 08:47",ip:"10.0.4.9"},
  ],
  flags:[
    {key:"batch_v2",name:"批量执行引擎 v2",desc:"新的差异预览与分组执行管线",enabled:true,rollout:12,section:"执行"},
    {key:"conflict_auto_merge",name:"冲突自动合并建议",desc:"对非价格字段给出合并建议（仍需人工确认）",enabled:false,rollout:0,section:"执行"},
    {key:"sellerhub_connector",name:"SellerHub 连接器",desc:"启用 SellerHub 平台集成",enabled:true,rollout:100,section:"连接器"},
    {key:"afternic_api_write",name:"Afternic 价格写入 API",desc:"绕过 CSV 人工上传（灰度）",enabled:false,rollout:5,section:"连接器"},
    {key:"multi_workspace",name:"多 Workspace 隔离",desc:"仅 Portfolio 方案可见",enabled:true,rollout:100,section:"方案"},
    {key:"web_execution",name:"网页端执行（实验）",desc:"允许在 account-web 提交低风险修改",enabled:false,rollout:0,section:"实验"},
  ],
  announcements:[
    {id:"ANN-0043",title:"0.9.0 发布：议价交割闭环",audience:"全部客户",status:"published",date:"昨日 10:30",author:"王运维"},
    {id:"ANN-0044",title:"me-south-1 区域维护窗口 · 08-20 02:00 UTC",audience:"中东区客户",status:"scheduled",date:"08-20 02:00",author:"王运维"},
    {id:"ANN-0045",title:"新增 SellerHub 连接器指南",audience:"Professional · Portfolio",status:"draft",date:"—",author:"李工"},
    {id:"ANN-0042",title:"安全提示：为账户启用 2FA",audience:"全部客户",status:"published",date:"08-12 09:00",author:"王运维"},
  ],
};
