[package]
name = "gooddealer-local-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gooddealer-secure-host-core = { path = "../secure-host-core" }

[dev-dependencies]
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = "=0.10.9"
tempfile = "=3.27.0"

[lints]
workspace = true
