import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";

import { tauriCommandPolicyErrors } from "./tauri-command-policy.mjs";

function writeFile(root, path, source) {
  const destination = join(root, path);
  mkdirSync(dirname(destination), { recursive: true });
  writeFileSync(destination, source);
}

function createFixture() {
  const root = mkdtempSync(join(tmpdir(), "gooddealer-tauri-command-"));
  const commands = ["local_business_status", "local_domain_asset_upsert", "local_portfolio_read"];
  writeFile(root, "apps/desktop/src-tauri/build.rs", `AppManifest::new().commands(&[${commands.map((command) => `"${command}"`).join(",")}])\n`);
  writeFile(root, "apps/desktop/src-tauri/src/main.rs", `tauri::generate_handler![${commands.join(",")}]\n`);
  writeFile(root, "apps/desktop/src-tauri/src/handler.rs", commands.map((command) => `#[tauri::command]\nfn ${command}() {}`).join("\n"));
  writeFile(root, "apps/desktop/src/adapters/tauri/index.ts", commands.map((command) => `"${command}"`).join("\n"));
  writeFile(
    root,
    "apps/desktop/src-tauri/capabilities/local-app.json",
    `${JSON.stringify({
      $schema: "../gen/schemas/desktop-schema.json",
      identifier: "local-app",
      description: "Local application shell with narrow local-business commands.",
      webviews: ["local-app"],
      permissions: ["core:default", ...commands.map((command) => `allow-${command.replaceAll("_", "-")}`)],
    })}\n`,
  );
  for (const command of commands) {
    writeFile(root, `apps/desktop/src-tauri/permissions/autogenerated/${command}.toml`, `identifier = "allow-${command.replaceAll("_", "-")}"\n`);
  }
  return root;
}

function useFixture(t) {
  const root = createFixture();
  t.after(() => rmSync(root, { recursive: true, force: true }));
  return root;
}

test("the repository Desktop bridge exposes exactly the reviewed local-business commands", () => {
  assert.deepEqual(tauriCommandPolicyErrors(), []);
});

test("rejects an unreviewed command or a missing reviewed command in each Desktop surface", (t) => {
  const mutations = [
    ["apps/desktop/src-tauri/build.rs", 'AppManifest::new().commands(&["unreviewed_command"])'],
    ["apps/desktop/src-tauri/src/main.rs", "tauri::generate_handler![unreviewed_command]"],
    ["apps/desktop/src-tauri/src/handler.rs", "#[tauri::command]\nfn unreviewed_command() {}"],
  ];
  for (const [path, source] of mutations) {
    const root = useFixture(t);
    writeFileSync(join(root, path), source);
    assert.ok(tauriCommandPolicyErrors({ root }).some((error) => error.includes("differs from reviewed")), path);
  }

  const capabilityRoot = useFixture(t);
  writeFile(
    capabilityRoot,
    "apps/desktop/src-tauri/capabilities/local-app.json",
    `${JSON.stringify({
      $schema: "../gen/schemas/desktop-schema.json",
      identifier: "local-app",
      description: "Local application shell with narrow local-business commands.",
      webviews: ["local-app"],
      permissions: ["allow-unreviewed-command"],
    })}\n`,
  );
  assert.ok(tauriCommandPolicyErrors({ root: capabilityRoot }).some((error) => error.includes("capability command set")));
});

test("rejects missing, symbolic-link, and adapter structural inputs", (t) => {
  const missingRoot = useFixture(t);
  rmSync(join(missingRoot, "apps/desktop/src-tauri/src/main.rs"));
  assert.ok(tauriCommandPolicyErrors({ root: missingRoot }).some((error) => error.includes("regular file")));

  const symlinkRoot = useFixture(t);
  rmSync(join(symlinkRoot, "apps/desktop/src-tauri/build.rs"));
  symlinkSync("missing-build", join(symlinkRoot, "apps/desktop/src-tauri/build.rs"));
  assert.ok(tauriCommandPolicyErrors({ root: symlinkRoot }).some((error) => error.includes("symlink")));

  const adapterRoot = useFixture(t);
  rmSync(join(adapterRoot, "apps/desktop/src/adapters/tauri/index.ts"));
  assert.ok(tauriCommandPolicyErrors({ root: adapterRoot }).some((error) => error.includes("regular file")));
});

test("rejects every capability broadening and custom permission surface", (t) => {
  const mutations = [
    ["missing commands", (value) => { value.permissions = [["core", "default"].join(":")]; }],
    ["window selector", (value) => { value.windows = ["*"]; }],
    ["extra WebView", (value) => { value.webviews.push("secondary"); }],
  ];
  for (const [name, mutate] of mutations) {
    const root = useFixture(t);
    const path = join(root, "apps/desktop/src-tauri/capabilities/local-app.json");
    const value = JSON.parse(readFileSync(path, "utf8"));
    mutate(value);
    writeFileSync(path, `${JSON.stringify(value)}\n`);
    assert.notDeepEqual(tauriCommandPolicyErrors({ root }), [], name);
  }

  const extraCapabilityRoot = useFixture(t);
  const retiredCapability = ["remote", "browser"].join("-");
  writeFile(
    extraCapabilityRoot,
    `apps/desktop/src-tauri/capabilities/${retiredCapability}.json`,
    `${JSON.stringify({ webviews: [retiredCapability], permissions: [] })}\n`,
  );
  assert.ok(tauriCommandPolicyErrors({ root: extraCapabilityRoot }).some((error) => error.includes("inventory")));

  const permissionRoot = useFixture(t);
  writeFile(permissionRoot, "apps/desktop/src-tauri/permissions/unreviewed.toml", "identifier = \"unreviewed\"\n");
  assert.ok(tauriCommandPolicyErrors({ root: permissionRoot }).some((error) => error.includes("inventory")));

  const capabilitySymlinkRoot = useFixture(t);
  const capabilityPath = join(capabilitySymlinkRoot, "apps/desktop/src-tauri/capabilities/local-app.json");
  rmSync(capabilityPath);
  symlinkSync("missing-capability", capabilityPath);
  assert.ok(tauriCommandPolicyErrors({ root: capabilitySymlinkRoot }).some((error) => error.includes("symlink")));
});
